### ISSUE TITLE
CRAG_inference.py

### ISSUE THREAD

**Issue by zsyggg** [HuskyInSalt/CRAG#19]
Hello, author, when I execute run_crag_inference.sh, the error shows that the single card graphics memory is insufficient, but the multi-card operation seems to be not set in the original code, right?
(zsy) (base) zhangshuaiyu@b410-4:~/CRAG$ bash run_crag_inference.sh 
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13990/13990 [17:10<00:00, 13.58it/s]
WARNING 08-18 02:11:58 config.py:1378] Casting torch.bfloat16 to torch.float16.
INFO 08-18 02:11:58 llm_engine.py:174] Initializing an LLM engine (v0.5.2) with config: model='/home/zhangshuaiyu/CRAG/selfrag/selfrag_llama2_7b', speculative_config=None, tokenizer='/home/zhangshuaiyu/CRAG/selfrag/selfrag_llama2_7b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/home/zhangshuaiyu/CRAG/selfrag/selfrag_llama2_7b, use_v2_block_manager=False, enable_prefix_caching=False)
INFO 08-18 02:12:09 model_runner.py:266] Loading model weights took 12.5532 GB
INFO 08-18 02:12:10 gpu_executor.py:86] # GPU blocks: 1071, # CPU blocks: 512
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zhangshuaiyu/CRAG/scripts/CRAG_Inference.py", line 268, in <module>
[rank0]:     main()
[rank0]:   File "/home/zhangshuaiyu/CRAG/scripts/CRAG_Inference.py", line 249, in main
[rank0]:     generator = LLM(model=args.generator_path, dtype="half")
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 150, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 421, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 263, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 375, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/executor/gpu_executor.py", line 89, in initialize_cache
[rank0]:     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/worker/worker.py", line 219, in initialize_cache
[rank0]:     self._init_cache_engine()
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/worker/worker.py", line 224, in _init_cache_engine
[rank0]:     self.cache_engine = [
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/worker/worker.py", line 225, in <listcomp>
[rank0]:     CacheEngine(self.cache_config, self.model_config,
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/worker/cache_engine.py", line 66, in __init__
[rank0]:     self.gpu_cache = self._allocate_kv_cache(
[rank0]:   File "/opt/miniconda3/envs/zsy/lib/python3.9/site-packages/vllm/worker/cache_engine.py", line 85, in _allocate_kv_cache
[rank0]:     torch.zeros(kv_cache_shape,
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 268.00 MiB. GPU

**Comment by HuskyInSalt** [comment]
Hi! `generator = LLM(model=args.generator_path, dtype="half")` utilized single GPU in our code, you can add the parameter `tensor_parallel_size` for multiple-GPU inference.
